root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server ./cmd/server"
  bin = "./tmp/server"
  include_ext = ["go"]
  exclude_dir = ["tmp", "bin", "static", "ml", "migrations"]
  exclude_regex = ["_test\\.go$"]
  delay = 300
