// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const adminGetProblemStateForUpdate = `-- name: AdminGetProblemStateForUpdate :one
SELECT state FROM problems WHERE id = $1 FOR UPDATE
`

func (q *Queries) AdminGetProblemStateForUpdate(ctx context.Context, id uuid.UUID) (ProblemState, error) {
	row := q.db.QueryRow(ctx, adminGetProblemStateForUpdate, id)
	var state ProblemState
	err := row.Scan(&state)
	return state, err
}

const adminInsertStateEvent = `-- name: AdminInsertStateEvent :exec
INSERT INTO problem_state_events (id, problem_id, from_state, to_state, actor_id, reason)
VALUES ($1, $2, $3, $4, $5, $6)
`

type AdminInsertStateEventParams struct {
	ID        uuid.UUID
	ProblemID uuid.UUID
	FromState ProblemState
	ToState   ProblemState
	ActorID   *uuid.UUID
	Reason    string
}

func (q *Queries) AdminInsertStateEvent(ctx context.Context, arg AdminInsertStateEventParams) error {
	_, err := q.db.Exec(ctx, adminInsertStateEvent,
		arg.ID,
		arg.ProblemID,
		arg.FromState,
		arg.ToState,
		arg.ActorID,
		arg.Reason,
	)
	return err
}

const adminListOpenReports = `-- name: AdminListOpenReports :many

SELECT
  r.id,
  r.target_kind,
  r.target_id,
  r.reason,
  r.created_at,
  rep.handle AS reporter_handle,
  COALESCE(pr.title, '')::text AS target_title,
  COALESCE(left(pr.current_process, 280), left(sr.body, 280), '')::text AS target_excerpt,
  COALESCE(pr.problem_id::text, s.problem_id::text, '')::text AS target_problem_id,
  COALESCE(COALESCE(pr.author_display, sr.author_display) = 'anonymous', false)::boolean AS target_anonymous,
  (CASE
     WHEN r.target_kind = 'user' OR COALESCE(pr.author_display, sr.author_display) = 'named' THEN COALESCE(tu.handle, '')
     ELSE ''
   END)::text AS target_handle,
  (tu.suspended_at IS NOT NULL)::boolean AS target_suspended,
  (tu.deleted_at IS NOT NULL)::boolean AS target_deleted,
  COALESCE(p.state::text, '')::text AS problem_state,
  COALESCE(p.on_meta_board, false)::boolean AS problem_on_meta
FROM reports r
JOIN users rep ON rep.id = r.reporter_id
LEFT JOIN problem_revisions pr ON r.target_kind = 'problem_revision' AND pr.id = r.target_id
LEFT JOIN solution_revisions sr ON r.target_kind = 'solution_revision' AND sr.id = r.target_id
LEFT JOIN solutions s ON s.id = sr.solution_id
LEFT JOIN problems p ON p.id = COALESCE(pr.problem_id, s.problem_id)
LEFT JOIN users tu ON tu.id = CASE WHEN r.target_kind = 'user' THEN r.target_id ELSE COALESCE(pr.author_id, sr.author_id) END
WHERE r.resolved_at IS NULL
  AND ($1::timestamptz IS NULL
       OR (r.created_at, r.id) > ($1::timestamptz, $2::uuid))
ORDER BY r.created_at, r.id
LIMIT $3
`

type AdminListOpenReportsParams struct {
	AfterCreated *time.Time
	AfterID      *uuid.UUID
	Lim          int32
}

type AdminListOpenReportsRow struct {
	ID              uuid.UUID
	TargetKind      string
	TargetID        uuid.UUID
	Reason          string
	CreatedAt       time.Time
	ReporterHandle  string
	TargetTitle     string
	TargetExcerpt   string
	TargetProblemID string
	TargetAnonymous bool
	TargetHandle    string
	TargetSuspended bool
	TargetDeleted   bool
	ProblemState    string
	ProblemOnMeta   bool
}

// /admin moderation. Admins are ADMIN_HANDLES; there is no admin role in the DB.
// Unresolved reports, oldest first, keyset on (created_at, id). For
// revisions the author's handle is returned only when the revision is named;
// author ids are never returned.
func (q *Queries) AdminListOpenReports(ctx context.Context, arg AdminListOpenReportsParams) ([]AdminListOpenReportsRow, error) {
	rows, err := q.db.Query(ctx, adminListOpenReports, arg.AfterCreated, arg.AfterID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListOpenReportsRow
	for rows.Next() {
		var i AdminListOpenReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.TargetKind,
			&i.TargetID,
			&i.Reason,
			&i.CreatedAt,
			&i.ReporterHandle,
			&i.TargetTitle,
			&i.TargetExcerpt,
			&i.TargetProblemID,
			&i.TargetAnonymous,
			&i.TargetHandle,
			&i.TargetSuspended,
			&i.TargetDeleted,
			&i.ProblemState,
			&i.ProblemOnMeta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminResolveReport = `-- name: AdminResolveReport :execrows
UPDATE reports SET resolved_at = now() WHERE id = $1 AND resolved_at IS NULL
`

func (q *Queries) AdminResolveReport(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, adminResolveReport, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminSetProblemState = `-- name: AdminSetProblemState :exec
UPDATE problems SET state = $2, updated_at = now() WHERE id = $1
`

type AdminSetProblemStateParams struct {
	ID    uuid.UUID
	State ProblemState
}

func (q *Queries) AdminSetProblemState(ctx context.Context, arg AdminSetProblemStateParams) error {
	_, err := q.db.Exec(ctx, adminSetProblemState, arg.ID, arg.State)
	return err
}

const adminSuspendUser = `-- name: AdminSuspendUser :execrows
UPDATE users SET suspended_at = COALESCE(suspended_at, now()) WHERE id = $1
`

func (q *Queries) AdminSuspendUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, adminSuspendUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminToggleMetaBoard = `-- name: AdminToggleMetaBoard :one
UPDATE problems SET on_meta_board = NOT on_meta_board, updated_at = now()
WHERE id = $1
RETURNING on_meta_board
`

func (q *Queries) AdminToggleMetaBoard(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, adminToggleMetaBoard, id)
	var on_meta_board bool
	err := row.Scan(&on_meta_board)
	return on_meta_board, err
}

const adminUnsuspendUser = `-- name: AdminUnsuspendUser :execrows
UPDATE users SET suspended_at = NULL WHERE id = $1
`

func (q *Queries) AdminUnsuspendUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, adminUnsuspendUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminZeroProblemVoteWeights = `-- name: AdminZeroProblemVoteWeights :many
UPDATE problem_revision_votes v SET weight = 0
FROM problem_revisions pr
WHERE v.revision_id = pr.id AND v.user_id = $1 AND v.weight <> 0
RETURNING pr.problem_id
`

// Zeroes every non-zero problem-revision vote by the user; returns the
// problem of each affected revision (one row per vote).
func (q *Queries) AdminZeroProblemVoteWeights(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, adminZeroProblemVoteWeights, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var problem_id uuid.UUID
		if err := rows.Scan(&problem_id); err != nil {
			return nil, err
		}
		items = append(items, problem_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminZeroSolutionVoteWeights = `-- name: AdminZeroSolutionVoteWeights :many
UPDATE solution_revision_votes v SET weight = 0
FROM solution_revisions sr, solutions s
WHERE v.revision_id = sr.id AND s.id = sr.solution_id AND v.user_id = $1 AND v.weight <> 0
RETURNING s.problem_id
`

// Same for solution-revision votes; returns the problem each solution is on.
func (q *Queries) AdminZeroSolutionVoteWeights(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, adminZeroSolutionVoteWeights, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var problem_id uuid.UUID
		if err := rows.Scan(&problem_id); err != nil {
			return nil, err
		}
		items = append(items, problem_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
