// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: interest.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countFounderInterest = `-- name: CountFounderInterest :one
SELECT count(*)::int8 FROM founder_interest WHERE problem_id = $1
`

func (q *Queries) CountFounderInterest(ctx context.Context, problemID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFounderInterest, problemID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteFounderInterest = `-- name: DeleteFounderInterest :execrows
DELETE FROM founder_interest WHERE problem_id = $1 AND user_id = $2
`

type DeleteFounderInterestParams struct {
	ProblemID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) DeleteFounderInterest(ctx context.Context, arg DeleteFounderInterestParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFounderInterest, arg.ProblemID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertFounderInterest = `-- name: InsertFounderInterest :execrows

INSERT INTO founder_interest (problem_id, user_id, created_at)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type InsertFounderInterestParams struct {
	ProblemID uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
}

// Founder interest: "I'd consider building for this" toggle.
func (q *Queries) InsertFounderInterest(ctx context.Context, arg InsertFounderInterestParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertFounderInterest, arg.ProblemID, arg.UserID, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
