// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DisplayMode string

const (
	DisplayModeNamed     DisplayMode = "named"
	DisplayModeAnonymous DisplayMode = "anonymous"
)

func (e *DisplayMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DisplayMode(s)
	case string:
		*e = DisplayMode(s)
	default:
		return fmt.Errorf("unsupported scan type for DisplayMode: %T", src)
	}
	return nil
}

type NullDisplayMode struct {
	DisplayMode DisplayMode
	Valid       bool // Valid is true if DisplayMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDisplayMode) Scan(value interface{}) error {
	if value == nil {
		ns.DisplayMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DisplayMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDisplayMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DisplayMode), nil
}

func (e DisplayMode) Valid() bool {
	switch e {
	case DisplayModeNamed,
		DisplayModeAnonymous:
		return true
	}
	return false
}

func AllDisplayModeValues() []DisplayMode {
	return []DisplayMode{
		DisplayModeNamed,
		DisplayModeAnonymous,
	}
}

type ProblemState string

const (
	ProblemStateOpen    ProblemState = "open"
	ProblemStateSolved  ProblemState = "solved"
	ProblemStateInvalid ProblemState = "invalid"
)

func (e *ProblemState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProblemState(s)
	case string:
		*e = ProblemState(s)
	default:
		return fmt.Errorf("unsupported scan type for ProblemState: %T", src)
	}
	return nil
}

type NullProblemState struct {
	ProblemState ProblemState
	Valid        bool // Valid is true if ProblemState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProblemState) Scan(value interface{}) error {
	if value == nil {
		ns.ProblemState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProblemState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProblemState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProblemState), nil
}

func (e ProblemState) Valid() bool {
	switch e {
	case ProblemStateOpen,
		ProblemStateSolved,
		ProblemStateInvalid:
		return true
	}
	return false
}

func AllProblemStateValues() []ProblemState {
	return []ProblemState{
		ProblemStateOpen,
		ProblemStateSolved,
		ProblemStateInvalid,
	}
}

type Provider string

const (
	ProviderLinkedin Provider = "linkedin"
	ProviderX        Provider = "x"
	ProviderGoogle   Provider = "google"
	ProviderGithub   Provider = "github"
	ProviderReddit   Provider = "reddit"
)

func (e *Provider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Provider(s)
	case string:
		*e = Provider(s)
	default:
		return fmt.Errorf("unsupported scan type for Provider: %T", src)
	}
	return nil
}

type NullProvider struct {
	Provider Provider
	Valid    bool // Valid is true if Provider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProvider) Scan(value interface{}) error {
	if value == nil {
		ns.Provider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Provider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Provider), nil
}

func (e Provider) Valid() bool {
	switch e {
	case ProviderLinkedin,
		ProviderX,
		ProviderGoogle,
		ProviderGithub,
		ProviderReddit:
		return true
	}
	return false
}

func AllProviderValues() []Provider {
	return []Provider{
		ProviderLinkedin,
		ProviderX,
		ProviderGoogle,
		ProviderGithub,
		ProviderReddit,
	}
}

type RiverJobState string

const (
	RiverJobStateAvailable RiverJobState = "available"
	RiverJobStateCancelled RiverJobState = "cancelled"
	RiverJobStateCompleted RiverJobState = "completed"
	RiverJobStateDiscarded RiverJobState = "discarded"
	RiverJobStatePending   RiverJobState = "pending"
	RiverJobStateRetryable RiverJobState = "retryable"
	RiverJobStateRunning   RiverJobState = "running"
	RiverJobStateScheduled RiverJobState = "scheduled"
)

func (e *RiverJobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiverJobState(s)
	case string:
		*e = RiverJobState(s)
	default:
		return fmt.Errorf("unsupported scan type for RiverJobState: %T", src)
	}
	return nil
}

type NullRiverJobState struct {
	RiverJobState RiverJobState
	Valid         bool // Valid is true if RiverJobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiverJobState) Scan(value interface{}) error {
	if value == nil {
		ns.RiverJobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiverJobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiverJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiverJobState), nil
}

func (e RiverJobState) Valid() bool {
	switch e {
	case RiverJobStateAvailable,
		RiverJobStateCancelled,
		RiverJobStateCompleted,
		RiverJobStateDiscarded,
		RiverJobStatePending,
		RiverJobStateRetryable,
		RiverJobStateRunning,
		RiverJobStateScheduled:
		return true
	}
	return false
}

func AllRiverJobStateValues() []RiverJobState {
	return []RiverJobState{
		RiverJobStateAvailable,
		RiverJobStateCancelled,
		RiverJobStateCompleted,
		RiverJobStateDiscarded,
		RiverJobStatePending,
		RiverJobStateRetryable,
		RiverJobStateRunning,
		RiverJobStateScheduled,
	}
}

type SolutionKind string

const (
	SolutionKindProcessChange  SolutionKind = "process_change"
	SolutionKindOffTheShelf    SolutionKind = "off_the_shelf"
	SolutionKindCustomSoftware SolutionKind = "custom_software"
	SolutionKindDontAutomate   SolutionKind = "dont_automate"
)

func (e *SolutionKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SolutionKind(s)
	case string:
		*e = SolutionKind(s)
	default:
		return fmt.Errorf("unsupported scan type for SolutionKind: %T", src)
	}
	return nil
}

type NullSolutionKind struct {
	SolutionKind SolutionKind
	Valid        bool // Valid is true if SolutionKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSolutionKind) Scan(value interface{}) error {
	if value == nil {
		ns.SolutionKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SolutionKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSolutionKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SolutionKind), nil
}

func (e SolutionKind) Valid() bool {
	switch e {
	case SolutionKindProcessChange,
		SolutionKindOffTheShelf,
		SolutionKindCustomSoftware,
		SolutionKindDontAutomate:
		return true
	}
	return false
}

func AllSolutionKindValues() []SolutionKind {
	return []SolutionKind{
		SolutionKindProcessChange,
		SolutionKindOffTheShelf,
		SolutionKindCustomSoftware,
		SolutionKindDontAutomate,
	}
}

type StandingTier string

const (
	StandingTierMember             StandingTier = "member"
	StandingTierDeclaredBackground StandingTier = "declared_background"
	StandingTierDomainContributor  StandingTier = "domain_contributor"
	StandingTierDomainExpert       StandingTier = "domain_expert"
)

func (e *StandingTier) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StandingTier(s)
	case string:
		*e = StandingTier(s)
	default:
		return fmt.Errorf("unsupported scan type for StandingTier: %T", src)
	}
	return nil
}

type NullStandingTier struct {
	StandingTier StandingTier
	Valid        bool // Valid is true if StandingTier is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStandingTier) Scan(value interface{}) error {
	if value == nil {
		ns.StandingTier, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StandingTier.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStandingTier) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StandingTier), nil
}

func (e StandingTier) Valid() bool {
	switch e {
	case StandingTierMember,
		StandingTierDeclaredBackground,
		StandingTierDomainContributor,
		StandingTierDomainExpert:
		return true
	}
	return false
}

func AllStandingTierValues() []StandingTier {
	return []StandingTier{
		StandingTierMember,
		StandingTierDeclaredBackground,
		StandingTierDomainContributor,
		StandingTierDomainExpert,
	}
}

type TriedOutcome string

const (
	TriedOutcomeWorked TriedOutcome = "worked"
	TriedOutcomePartly TriedOutcome = "partly"
	TriedOutcomeFailed TriedOutcome = "failed"
)

func (e *TriedOutcome) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TriedOutcome(s)
	case string:
		*e = TriedOutcome(s)
	default:
		return fmt.Errorf("unsupported scan type for TriedOutcome: %T", src)
	}
	return nil
}

type NullTriedOutcome struct {
	TriedOutcome TriedOutcome
	Valid        bool // Valid is true if TriedOutcome is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTriedOutcome) Scan(value interface{}) error {
	if value == nil {
		ns.TriedOutcome, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TriedOutcome.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTriedOutcome) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TriedOutcome), nil
}

func (e TriedOutcome) Valid() bool {
	switch e {
	case TriedOutcomeWorked,
		TriedOutcomePartly,
		TriedOutcomeFailed:
		return true
	}
	return false
}

func AllTriedOutcomeValues() []TriedOutcome {
	return []TriedOutcome{
		TriedOutcomeWorked,
		TriedOutcomePartly,
		TriedOutcomeFailed,
	}
}

type Domain struct {
	ID   int16
	Slug string
	Name string
}

type FounderInterest struct {
	ProblemID uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
}

type Identity struct {
	UserID      uuid.UUID
	Provider    Provider
	ProviderUid string
	ProfileUrl  *string
	CreatedAt   time.Time
}

type MergeSuggestion struct {
	ID          uuid.UUID
	ProblemAID  uuid.UUID
	ProblemBID  uuid.UUID
	Similarity  float32
	DismissedAt *time.Time
	CreatedAt   time.Time
}

type Problem struct {
	ID                   uuid.UUID
	DomainID             int16
	AuthorID             uuid.UUID
	AuthorDisplay        DisplayMode
	State                ProblemState
	SoftSolved           bool
	CurrentRevisionID    *uuid.UUID
	ForkedFromRevisionID *uuid.UUID
	Score                float64
	OnMetaBoard          bool
	IsSeed               bool
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type ProblemRevision struct {
	ID               uuid.UUID
	ProblemID        uuid.UUID
	ParentRevisionID *uuid.UUID
	AuthorID         uuid.UUID
	AuthorDisplay    DisplayMode
	Title            string
	CurrentProcess   string
	Pain             string
	Tried            string
	WhyNote          *string
	Score            float64
	VoteCount        int32
	Embedding        *string
	CreatedAt        time.Time
}

type ProblemRevisionVote struct {
	RevisionID uuid.UUID
	UserID     uuid.UUID
	Weight     float32
	CreatedAt  time.Time
}

type ProblemStateEvent struct {
	ID        uuid.UUID
	ProblemID uuid.UUID
	FromState ProblemState
	ToState   ProblemState
	ActorID   *uuid.UUID
	Reason    string
	CreatedAt time.Time
}

type ProblemStateVote struct {
	ProblemID uuid.UUID
	UserID    uuid.UUID
	ToState   ProblemState
	Weight    float32
	CreatedAt time.Time
}

type Report struct {
	ID         uuid.UUID
	ReporterID uuid.UUID
	TargetKind string
	TargetID   uuid.UUID
	Reason     string
	ResolvedAt *time.Time
	CreatedAt  time.Time
}

type RiverJob struct {
	ID           int64
	State        RiverJobState
	Attempt      int16
	MaxAttempts  int16
	AttemptedAt  *time.Time
	CreatedAt    time.Time
	FinalizedAt  *time.Time
	ScheduledAt  time.Time
	Priority     int16
	Args         []byte
	AttemptedBy  []string
	Errors       [][]byte
	Kind         string
	Metadata     []byte
	Queue        string
	Tags         []string
	UniqueKey    []byte
	UniqueStates pgtype.Bits
}

type RiverLeader struct {
	ElectedAt time.Time
	ExpiresAt time.Time
	LeaderID  string
	Name      string
}

type RiverNotification struct {
	ID        int64
	CreatedAt time.Time
	Payload   string
	Topic     string
}

type RiverQueue struct {
	Name      string
	CreatedAt time.Time
	Metadata  []byte
	PausedAt  *time.Time
	UpdatedAt time.Time
}

type Session struct {
	TokenHash []byte
	UserID    uuid.UUID
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Solution struct {
	ID                uuid.UUID
	ProblemID         uuid.UUID
	AuthorID          uuid.UUID
	AuthorDisplay     DisplayMode
	Kind              SolutionKind
	CurrentRevisionID *uuid.UUID
	Score             float64
	CreatedAt         time.Time
}

type SolutionRevision struct {
	ID               uuid.UUID
	SolutionID       uuid.UUID
	ParentRevisionID *uuid.UUID
	AuthorID         uuid.UUID
	AuthorDisplay    DisplayMode
	Body             string
	WhyNote          *string
	Score            float64
	VoteCount        int32
	CreatedAt        time.Time
}

type SolutionRevisionVote struct {
	RevisionID uuid.UUID
	UserID     uuid.UUID
	Weight     float32
	CreatedAt  time.Time
}

type SolutionTrial struct {
	SolutionID uuid.UUID
	UserID     uuid.UUID
	Outcome    TriedOutcome
	Note       *string
	CreatedAt  time.Time
}

type TrendingProblem struct {
	ProblemID  uuid.UUID
	ClusterID  int32
	Rank       int32
	ComputedAt time.Time
}

type User struct {
	ID                     uuid.UUID
	Handle                 string
	DisplayName            string
	InDirectory            bool
	DeclaredHistory        *string
	SuspendedAt            *time.Time
	DeletedAt              *time.Time
	CreatedAt              time.Time
	Email                  *string
	ContributionPreference string
	OnboardingCompleted    bool
}

type UserDomainStanding struct {
	UserID    uuid.UUID
	DomainID  int16
	Tier      StandingTier
	Points    float64
	UpdatedAt time.Time
}

type Vouch struct {
	VoucherID uuid.UUID
	VoucheeID uuid.UUID
	DomainID  int16
	CreatedAt time.Time
}
