// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: problems.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countNonSeedProblemsUpTo50 = `-- name: CountNonSeedProblemsUpTo50 :one
SELECT count(*)::int8 FROM (SELECT 1 FROM problems WHERE NOT is_seed LIMIT 50) s
`

// Bounded: stops counting at 50, which is all the pinning rule needs.
func (q *Queries) CountNonSeedProblemsUpTo50(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countNonSeedProblemsUpTo50)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getProblemForWrite = `-- name: GetProblemForWrite :one
SELECT id, domain_id, author_id, state, current_revision_id
FROM problems WHERE id = $1
`

type GetProblemForWriteRow struct {
	ID                uuid.UUID
	DomainID          int16
	AuthorID          uuid.UUID
	State             ProblemState
	CurrentRevisionID *uuid.UUID
}

func (q *Queries) GetProblemForWrite(ctx context.Context, id uuid.UUID) (GetProblemForWriteRow, error) {
	row := q.db.QueryRow(ctx, getProblemForWrite, id)
	var i GetProblemForWriteRow
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.AuthorID,
		&i.State,
		&i.CurrentRevisionID,
	)
	return i, err
}

const getProblemPage = `-- name: GetProblemPage :one
SELECT p.id, p.state, p.soft_solved, p.on_meta_board, p.is_seed, p.created_at,
       d.slug AS domain_slug, d.name AS domain_name,
       r.id AS revision_id, r.title, r.current_process, r.pain, r.tried,
       r.vote_count, r.score, r.created_at AS revision_created_at,
       (r.parent_revision_id IS NOT NULL)::bool AS is_revised,
       r.author_display AS revision_author_display, ru.handle AS revision_author_handle,
       (ru.deleted_at IS NOT NULL)::bool AS revision_author_deleted,
       COALESCE(rs.tier::text, 'member')::text AS revision_author_tier,
       p.author_display AS poster_display, pu.handle AS poster_handle,
       (pu.deleted_at IS NOT NULL)::bool AS poster_deleted,
       COALESCE(ps.tier::text, 'member')::text AS poster_tier,
       ((p.author_id = $1::uuid) IS TRUE)::bool AS viewer_is_poster,
       ((r.author_id = $1::uuid) IS TRUE)::bool AS viewer_is_revision_author,
       EXISTS (SELECT 1 FROM problem_revision_votes v
               WHERE v.revision_id = r.id AND v.user_id = $1::uuid)::bool AS viewer_voted,
       (SELECT count(*) FROM founder_interest fi WHERE fi.problem_id = p.id)::int8 AS interest_count,
       EXISTS (SELECT 1 FROM founder_interest fi
               WHERE fi.problem_id = p.id AND fi.user_id = $1::uuid)::bool AS viewer_interested,
       fr.problem_id AS forked_from_problem_id, fr.title AS forked_from_title,
       COALESCE((SELECT jsonb_agg(jsonb_build_object('id', f.id, 'title', fcr.title) ORDER BY f.created_at)
                 FROM problems f
                 JOIN problem_revisions fcr ON fcr.id = f.current_revision_id
                 WHERE f.forked_from_revision_id IN
                       (SELECT pr.id FROM problem_revisions pr WHERE pr.problem_id = p.id)),
                '[]'::jsonb)::jsonb AS forks
FROM problems p
JOIN domains d ON d.id = p.domain_id
JOIN problem_revisions r ON r.id = p.current_revision_id
JOIN users ru ON ru.id = r.author_id
JOIN users pu ON pu.id = p.author_id
LEFT JOIN user_domain_standing rs ON rs.user_id = r.author_id AND rs.domain_id = p.domain_id
LEFT JOIN user_domain_standing ps ON ps.user_id = p.author_id AND ps.domain_id = p.domain_id
LEFT JOIN problem_revisions fr ON fr.id = p.forked_from_revision_id
WHERE p.id = $2
`

type GetProblemPageParams struct {
	ViewerID *uuid.UUID
	ID       uuid.UUID
}

type GetProblemPageRow struct {
	ID                     uuid.UUID
	State                  ProblemState
	SoftSolved             bool
	OnMetaBoard            bool
	IsSeed                 bool
	CreatedAt              time.Time
	DomainSlug             string
	DomainName             string
	RevisionID             uuid.UUID
	Title                  string
	CurrentProcess         string
	Pain                   string
	Tried                  string
	VoteCount              int32
	Score                  float64
	RevisionCreatedAt      time.Time
	IsRevised              bool
	RevisionAuthorDisplay  DisplayMode
	RevisionAuthorHandle   string
	RevisionAuthorDeleted  bool
	RevisionAuthorTier     string
	PosterDisplay          DisplayMode
	PosterHandle           string
	PosterDeleted          bool
	PosterTier             string
	ViewerIsPoster         bool
	ViewerIsRevisionAuthor bool
	ViewerVoted            bool
	InterestCount          int64
	ViewerInterested       bool
	ForkedFromProblemID    *uuid.UUID
	ForkedFromTitle        *string
	Forks                  []byte
}

func (q *Queries) GetProblemPage(ctx context.Context, arg GetProblemPageParams) (GetProblemPageRow, error) {
	row := q.db.QueryRow(ctx, getProblemPage, arg.ViewerID, arg.ID)
	var i GetProblemPageRow
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.SoftSolved,
		&i.OnMetaBoard,
		&i.IsSeed,
		&i.CreatedAt,
		&i.DomainSlug,
		&i.DomainName,
		&i.RevisionID,
		&i.Title,
		&i.CurrentProcess,
		&i.Pain,
		&i.Tried,
		&i.VoteCount,
		&i.Score,
		&i.RevisionCreatedAt,
		&i.IsRevised,
		&i.RevisionAuthorDisplay,
		&i.RevisionAuthorHandle,
		&i.RevisionAuthorDeleted,
		&i.RevisionAuthorTier,
		&i.PosterDisplay,
		&i.PosterHandle,
		&i.PosterDeleted,
		&i.PosterTier,
		&i.ViewerIsPoster,
		&i.ViewerIsRevisionAuthor,
		&i.ViewerVoted,
		&i.InterestCount,
		&i.ViewerInterested,
		&i.ForkedFromProblemID,
		&i.ForkedFromTitle,
		&i.Forks,
	)
	return i, err
}

const insertProblem = `-- name: InsertProblem :exec

INSERT INTO problems (id, domain_id, author_id, author_display, current_revision_id,
                      forked_from_revision_id, is_seed, created_at, updated_at)
VALUES ($1, $2, $3, $4,
        $5, $6, $7,
        $8, $8)
`

type InsertProblemParams struct {
	ID                   uuid.UUID
	DomainID             int16
	AuthorID             uuid.UUID
	AuthorDisplay        DisplayMode
	CurrentRevisionID    *uuid.UUID
	ForkedFromRevisionID *uuid.UUID
	IsSeed               bool
	Now                  time.Time
}

// Problems: creation, the problem page and the keyset-paginated lists.
// Every list reads stored scores; nothing is computed from vote rows here.
// current_revision_id is set here; its FK is deferred until the first
// revision is inserted later in the same transaction.
func (q *Queries) InsertProblem(ctx context.Context, arg InsertProblemParams) error {
	_, err := q.db.Exec(ctx, insertProblem,
		arg.ID,
		arg.DomainID,
		arg.AuthorID,
		arg.AuthorDisplay,
		arg.CurrentRevisionID,
		arg.ForkedFromRevisionID,
		arg.IsSeed,
		arg.Now,
	)
	return err
}

const listFrontPage = `-- name: ListFrontPage :many
SELECT p.id, p.score, p.created_at, p.state, p.soft_solved, p.is_seed,
       d.slug AS domain_slug, d.name AS domain_name, r.title, r.vote_count,
       p.author_display, u.handle AS author_handle, (u.deleted_at IS NOT NULL)::bool AS author_deleted,
       COALESCE(st.tier::text, 'member')::text AS author_tier
FROM problems p
JOIN domains d ON d.id = p.domain_id
JOIN problem_revisions r ON r.id = p.current_revision_id
JOIN users u ON u.id = p.author_id
LEFT JOIN user_domain_standing st ON st.user_id = p.author_id AND st.domain_id = p.domain_id
WHERE p.state = 'open' AND NOT p.soft_solved AND NOT p.on_meta_board
  AND (NOT $1::bool OR NOT p.is_seed)
  AND (NOT $2::bool OR (p.score, p.id) < ($3::float8, $4::uuid))
ORDER BY p.score DESC, p.id DESC
LIMIT $5
`

type ListFrontPageParams struct {
	ExcludeSeeds bool
	HasAfter     bool
	AfterScore   float64
	AfterID      uuid.UUID
	Lim          int32
}

type ListFrontPageRow struct {
	ID            uuid.UUID
	Score         float64
	CreatedAt     time.Time
	State         ProblemState
	SoftSolved    bool
	IsSeed        bool
	DomainSlug    string
	DomainName    string
	Title         string
	VoteCount     int32
	AuthorDisplay DisplayMode
	AuthorHandle  string
	AuthorDeleted bool
	AuthorTier    string
}

func (q *Queries) ListFrontPage(ctx context.Context, arg ListFrontPageParams) ([]ListFrontPageRow, error) {
	rows, err := q.db.Query(ctx, listFrontPage,
		arg.ExcludeSeeds,
		arg.HasAfter,
		arg.AfterScore,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFrontPageRow
	for rows.Next() {
		var i ListFrontPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Score,
			&i.CreatedAt,
			&i.State,
			&i.SoftSolved,
			&i.IsSeed,
			&i.DomainSlug,
			&i.DomainName,
			&i.Title,
			&i.VoteCount,
			&i.AuthorDisplay,
			&i.AuthorHandle,
			&i.AuthorDeleted,
			&i.AuthorTier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetaBoard = `-- name: ListMetaBoard :many
SELECT p.id, p.score, p.created_at, p.state, p.soft_solved, p.is_seed,
       d.slug AS domain_slug, d.name AS domain_name, r.title, r.vote_count,
       p.author_display, u.handle AS author_handle, (u.deleted_at IS NOT NULL)::bool AS author_deleted,
       COALESCE(st.tier::text, 'member')::text AS author_tier
FROM problems p
JOIN domains d ON d.id = p.domain_id
JOIN problem_revisions r ON r.id = p.current_revision_id
JOIN users u ON u.id = p.author_id
LEFT JOIN user_domain_standing st ON st.user_id = p.author_id AND st.domain_id = p.domain_id
WHERE p.on_meta_board
  AND (NOT $1::bool OR (p.score, p.id) < ($2::float8, $3::uuid))
ORDER BY p.score DESC, p.id DESC
LIMIT $4
`

type ListMetaBoardParams struct {
	HasAfter   bool
	AfterScore float64
	AfterID    uuid.UUID
	Lim        int32
}

type ListMetaBoardRow struct {
	ID            uuid.UUID
	Score         float64
	CreatedAt     time.Time
	State         ProblemState
	SoftSolved    bool
	IsSeed        bool
	DomainSlug    string
	DomainName    string
	Title         string
	VoteCount     int32
	AuthorDisplay DisplayMode
	AuthorHandle  string
	AuthorDeleted bool
	AuthorTier    string
}

func (q *Queries) ListMetaBoard(ctx context.Context, arg ListMetaBoardParams) ([]ListMetaBoardRow, error) {
	rows, err := q.db.Query(ctx, listMetaBoard,
		arg.HasAfter,
		arg.AfterScore,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMetaBoardRow
	for rows.Next() {
		var i ListMetaBoardRow
		if err := rows.Scan(
			&i.ID,
			&i.Score,
			&i.CreatedAt,
			&i.State,
			&i.SoftSolved,
			&i.IsSeed,
			&i.DomainSlug,
			&i.DomainName,
			&i.Title,
			&i.VoteCount,
			&i.AuthorDisplay,
			&i.AuthorHandle,
			&i.AuthorDeleted,
			&i.AuthorTier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPinnedSeedProblems = `-- name: ListPinnedSeedProblems :many
SELECT p.id, p.score, p.created_at, p.state, p.soft_solved, p.is_seed,
       d.slug AS domain_slug, d.name AS domain_name, r.title, r.vote_count,
       p.author_display, u.handle AS author_handle, (u.deleted_at IS NOT NULL)::bool AS author_deleted,
       COALESCE(st.tier::text, 'member')::text AS author_tier
FROM problems p
JOIN domains d ON d.id = p.domain_id
JOIN problem_revisions r ON r.id = p.current_revision_id
JOIN users u ON u.id = p.author_id
LEFT JOIN user_domain_standing st ON st.user_id = p.author_id AND st.domain_id = p.domain_id
WHERE p.is_seed AND p.state = 'open' AND NOT p.soft_solved AND NOT p.on_meta_board
ORDER BY p.score DESC, p.id DESC
LIMIT 50
`

type ListPinnedSeedProblemsRow struct {
	ID            uuid.UUID
	Score         float64
	CreatedAt     time.Time
	State         ProblemState
	SoftSolved    bool
	IsSeed        bool
	DomainSlug    string
	DomainName    string
	Title         string
	VoteCount     int32
	AuthorDisplay DisplayMode
	AuthorHandle  string
	AuthorDeleted bool
	AuthorTier    string
}

func (q *Queries) ListPinnedSeedProblems(ctx context.Context) ([]ListPinnedSeedProblemsRow, error) {
	rows, err := q.db.Query(ctx, listPinnedSeedProblems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPinnedSeedProblemsRow
	for rows.Next() {
		var i ListPinnedSeedProblemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Score,
			&i.CreatedAt,
			&i.State,
			&i.SoftSolved,
			&i.IsSeed,
			&i.DomainSlug,
			&i.DomainName,
			&i.Title,
			&i.VoteCount,
			&i.AuthorDisplay,
			&i.AuthorHandle,
			&i.AuthorDeleted,
			&i.AuthorTier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProblemsNew = `-- name: ListProblemsNew :many
SELECT p.id, p.score, p.created_at, p.state, p.soft_solved, p.is_seed,
       d.slug AS domain_slug, d.name AS domain_name, r.title, r.vote_count,
       p.author_display, u.handle AS author_handle, (u.deleted_at IS NOT NULL)::bool AS author_deleted,
       COALESCE(st.tier::text, 'member')::text AS author_tier
FROM problems p
JOIN domains d ON d.id = p.domain_id
JOIN problem_revisions r ON r.id = p.current_revision_id
JOIN users u ON u.id = p.author_id
LEFT JOIN user_domain_standing st ON st.user_id = p.author_id AND st.domain_id = p.domain_id
WHERE NOT p.on_meta_board
  AND ($1::problem_state IS NULL OR p.state = $1::problem_state)
  AND ($2::text IS NULL OR d.slug = $2::text)
  AND (NOT $3::bool OR (p.created_at, p.id) < ($4::timestamptz, $5::uuid))
ORDER BY p.created_at DESC, p.id DESC
LIMIT $6
`

type ListProblemsNewParams struct {
	State          *ProblemState
	DomainSlug     *string
	HasAfter       bool
	AfterCreatedAt time.Time
	AfterID        uuid.UUID
	Lim            int32
}

type ListProblemsNewRow struct {
	ID            uuid.UUID
	Score         float64
	CreatedAt     time.Time
	State         ProblemState
	SoftSolved    bool
	IsSeed        bool
	DomainSlug    string
	DomainName    string
	Title         string
	VoteCount     int32
	AuthorDisplay DisplayMode
	AuthorHandle  string
	AuthorDeleted bool
	AuthorTier    string
}

func (q *Queries) ListProblemsNew(ctx context.Context, arg ListProblemsNewParams) ([]ListProblemsNewRow, error) {
	rows, err := q.db.Query(ctx, listProblemsNew,
		arg.State,
		arg.DomainSlug,
		arg.HasAfter,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProblemsNewRow
	for rows.Next() {
		var i ListProblemsNewRow
		if err := rows.Scan(
			&i.ID,
			&i.Score,
			&i.CreatedAt,
			&i.State,
			&i.SoftSolved,
			&i.IsSeed,
			&i.DomainSlug,
			&i.DomainName,
			&i.Title,
			&i.VoteCount,
			&i.AuthorDisplay,
			&i.AuthorHandle,
			&i.AuthorDeleted,
			&i.AuthorTier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProblemsTop = `-- name: ListProblemsTop :many
SELECT p.id, p.score, p.created_at, p.state, p.soft_solved, p.is_seed,
       d.slug AS domain_slug, d.name AS domain_name, r.title, r.vote_count,
       p.author_display, u.handle AS author_handle, (u.deleted_at IS NOT NULL)::bool AS author_deleted,
       COALESCE(st.tier::text, 'member')::text AS author_tier
FROM problems p
JOIN domains d ON d.id = p.domain_id
JOIN problem_revisions r ON r.id = p.current_revision_id
JOIN users u ON u.id = p.author_id
LEFT JOIN user_domain_standing st ON st.user_id = p.author_id AND st.domain_id = p.domain_id
WHERE NOT p.on_meta_board
  AND ($1::problem_state IS NULL OR p.state = $1::problem_state)
  AND ($2::text IS NULL OR d.slug = $2::text)
  AND (NOT $3::bool OR (p.score, p.id) < ($4::float8, $5::uuid))
ORDER BY p.score DESC, p.id DESC
LIMIT $6
`

type ListProblemsTopParams struct {
	State      *ProblemState
	DomainSlug *string
	HasAfter   bool
	AfterScore float64
	AfterID    uuid.UUID
	Lim        int32
}

type ListProblemsTopRow struct {
	ID            uuid.UUID
	Score         float64
	CreatedAt     time.Time
	State         ProblemState
	SoftSolved    bool
	IsSeed        bool
	DomainSlug    string
	DomainName    string
	Title         string
	VoteCount     int32
	AuthorDisplay DisplayMode
	AuthorHandle  string
	AuthorDeleted bool
	AuthorTier    string
}

func (q *Queries) ListProblemsTop(ctx context.Context, arg ListProblemsTopParams) ([]ListProblemsTopRow, error) {
	rows, err := q.db.Query(ctx, listProblemsTop,
		arg.State,
		arg.DomainSlug,
		arg.HasAfter,
		arg.AfterScore,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProblemsTopRow
	for rows.Next() {
		var i ListProblemsTopRow
		if err := rows.Scan(
			&i.ID,
			&i.Score,
			&i.CreatedAt,
			&i.State,
			&i.SoftSolved,
			&i.IsSeed,
			&i.DomainSlug,
			&i.DomainName,
			&i.Title,
			&i.VoteCount,
			&i.AuthorDisplay,
			&i.AuthorHandle,
			&i.AuthorDeleted,
			&i.AuthorTier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
