// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listNamedContributions = `-- name: ListNamedContributions :many
SELECT c.kind, c.problem_id, c.title, c.is_first, c.created_at
FROM (
  SELECT 'problem'::text AS kind, pr.problem_id, pr.title,
         (pr.parent_revision_id IS NULL)::boolean AS is_first, pr.created_at, pr.id
  FROM problem_revisions pr
  WHERE pr.author_id = $1 AND pr.author_display = 'named'
  UNION ALL
  SELECT 'solution'::text, s.problem_id, cur.title,
         (sr.parent_revision_id IS NULL)::boolean, sr.created_at, sr.id
  FROM solution_revisions sr
  JOIN solutions s ON s.id = sr.solution_id
  JOIN problems p ON p.id = s.problem_id
  JOIN problem_revisions cur ON cur.id = p.current_revision_id
  WHERE sr.author_id = $1 AND sr.author_display = 'named'
) c
ORDER BY c.created_at DESC, c.id DESC
LIMIT $2
`

type ListNamedContributionsParams struct {
	UserID  uuid.UUID
	MaxRows int32
}

type ListNamedContributionsRow struct {
	Kind      string
	ProblemID uuid.UUID
	Title     string
	IsFirst   bool
	CreatedAt time.Time
}

// A user's public profile: named problem and solution revisions only.
// Anonymous rows are filtered here and must never reach the profile page.
func (q *Queries) ListNamedContributions(ctx context.Context, arg ListNamedContributionsParams) ([]ListNamedContributionsRow, error) {
	rows, err := q.db.Query(ctx, listNamedContributions, arg.UserID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNamedContributionsRow
	for rows.Next() {
		var i ListNamedContributionsRow
		if err := rows.Scan(
			&i.Kind,
			&i.ProblemID,
			&i.Title,
			&i.IsFirst,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
