// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: solutions.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getSolutionForWrite = `-- name: GetSolutionForWrite :one
SELECT s.id, s.problem_id, s.current_revision_id, p.state, p.domain_id
FROM solutions s
JOIN problems p ON p.id = s.problem_id
WHERE s.id = $1
`

type GetSolutionForWriteRow struct {
	ID                uuid.UUID
	ProblemID         uuid.UUID
	CurrentRevisionID *uuid.UUID
	State             ProblemState
	DomainID          int16
}

func (q *Queries) GetSolutionForWrite(ctx context.Context, id uuid.UUID) (GetSolutionForWriteRow, error) {
	row := q.db.QueryRow(ctx, getSolutionForWrite, id)
	var i GetSolutionForWriteRow
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.CurrentRevisionID,
		&i.State,
		&i.DomainID,
	)
	return i, err
}

const getSolutionRevisionOwner = `-- name: GetSolutionRevisionOwner :one
SELECT id, solution_id FROM solution_revisions WHERE id = $1
`

type GetSolutionRevisionOwnerRow struct {
	ID         uuid.UUID
	SolutionID uuid.UUID
}

func (q *Queries) GetSolutionRevisionOwner(ctx context.Context, id uuid.UUID) (GetSolutionRevisionOwnerRow, error) {
	row := q.db.QueryRow(ctx, getSolutionRevisionOwner, id)
	var i GetSolutionRevisionOwnerRow
	err := row.Scan(&i.ID, &i.SolutionID)
	return i, err
}

const getTopSolution = `-- name: GetTopSolution :one
SELECT s.id, r.vote_count
FROM solutions s
JOIN solution_revisions r ON r.id = s.current_revision_id
WHERE s.problem_id = $1
ORDER BY s.score DESC, s.id
LIMIT 1
`

type GetTopSolutionRow struct {
	ID        uuid.UUID
	VoteCount int32
}

// The problem's top solution by stored score, with its current revision's raw vote count.
func (q *Queries) GetTopSolution(ctx context.Context, problemID uuid.UUID) (GetTopSolutionRow, error) {
	row := q.db.QueryRow(ctx, getTopSolution, problemID)
	var i GetTopSolutionRow
	err := row.Scan(&i.ID, &i.VoteCount)
	return i, err
}

const insertSolution = `-- name: InsertSolution :exec

INSERT INTO solutions (id, problem_id, author_id, author_display, kind, current_revision_id, created_at)
VALUES ($1, $2, $3, $4,
        $5, $6, $7)
`

type InsertSolutionParams struct {
	ID                uuid.UUID
	ProblemID         uuid.UUID
	AuthorID          uuid.UUID
	AuthorDisplay     DisplayMode
	Kind              SolutionKind
	CurrentRevisionID *uuid.UUID
	CreatedAt         time.Time
}

// Solutions: same shape as problems (identity + immutable revisions), plus
// "tried it" outcomes.
func (q *Queries) InsertSolution(ctx context.Context, arg InsertSolutionParams) error {
	_, err := q.db.Exec(ctx, insertSolution,
		arg.ID,
		arg.ProblemID,
		arg.AuthorID,
		arg.AuthorDisplay,
		arg.Kind,
		arg.CurrentRevisionID,
		arg.CreatedAt,
	)
	return err
}

const insertSolutionRevision = `-- name: InsertSolutionRevision :exec
INSERT INTO solution_revisions (id, solution_id, parent_revision_id, author_id, author_display,
                                body, why_note, created_at)
VALUES ($1, $2, $3, $4,
        $5, $6, $7, $8)
`

type InsertSolutionRevisionParams struct {
	ID               uuid.UUID
	SolutionID       uuid.UUID
	ParentRevisionID *uuid.UUID
	AuthorID         uuid.UUID
	AuthorDisplay    DisplayMode
	Body             string
	WhyNote          *string
	CreatedAt        time.Time
}

func (q *Queries) InsertSolutionRevision(ctx context.Context, arg InsertSolutionRevisionParams) error {
	_, err := q.db.Exec(ctx, insertSolutionRevision,
		arg.ID,
		arg.SolutionID,
		arg.ParentRevisionID,
		arg.AuthorID,
		arg.AuthorDisplay,
		arg.Body,
		arg.WhyNote,
		arg.CreatedAt,
	)
	return err
}

const listProblemSolutions = `-- name: ListProblemSolutions :many
SELECT s.id, s.kind, s.score, s.created_at,
       r.id AS revision_id, r.body, r.vote_count, r.created_at AS revision_created_at,
       (r.parent_revision_id IS NOT NULL)::bool AS is_revised,
       r.author_display, u.handle AS author_handle, (u.deleted_at IS NOT NULL)::bool AS author_deleted,
       COALESCE(st.tier::text, 'member')::text AS author_tier,
       ((r.author_id = $1::uuid) IS TRUE)::bool AS viewer_is_author,
       EXISTS (SELECT 1 FROM solution_revision_votes v
               WHERE v.revision_id = r.id AND v.user_id = $1::uuid)::bool AS viewer_voted,
       t.worked::int8 AS worked, t.partly::int8 AS partly, t.failed::int8 AS failed,
       COALESCE((SELECT jsonb_agg(jsonb_build_object('outcome', n.outcome, 'note', n.note) ORDER BY n.created_at DESC)
                 FROM (SELECT tt.outcome, tt.note, tt.created_at FROM solution_trials tt
                       WHERE tt.solution_id = s.id AND tt.note IS NOT NULL AND tt.note <> ''
                       ORDER BY tt.created_at DESC LIMIT 3) n),
                '[]'::jsonb)::jsonb AS recent_notes,
       COALESCE((SELECT vt.outcome::text FROM solution_trials vt
                 WHERE vt.solution_id = s.id AND vt.user_id = $1::uuid), '')::text AS viewer_outcome
FROM solutions s
JOIN problems p ON p.id = s.problem_id
JOIN solution_revisions r ON r.id = s.current_revision_id
JOIN users u ON u.id = r.author_id
LEFT JOIN user_domain_standing st ON st.user_id = r.author_id AND st.domain_id = p.domain_id
CROSS JOIN LATERAL (
  SELECT count(*) FILTER (WHERE outcome = 'worked') AS worked,
         count(*) FILTER (WHERE outcome = 'partly') AS partly,
         count(*) FILTER (WHERE outcome = 'failed') AS failed
  FROM solution_trials WHERE solution_id = s.id
) t
WHERE s.problem_id = $2
ORDER BY s.score DESC, s.id
LIMIT 100
`

type ListProblemSolutionsParams struct {
	ViewerID  *uuid.UUID
	ProblemID uuid.UUID
}

type ListProblemSolutionsRow struct {
	ID                uuid.UUID
	Kind              SolutionKind
	Score             float64
	CreatedAt         time.Time
	RevisionID        uuid.UUID
	Body              string
	VoteCount         int32
	RevisionCreatedAt time.Time
	IsRevised         bool
	AuthorDisplay     DisplayMode
	AuthorHandle      string
	AuthorDeleted     bool
	AuthorTier        string
	ViewerIsAuthor    bool
	ViewerVoted       bool
	Worked            int64
	Partly            int64
	Failed            int64
	RecentNotes       []byte
	ViewerOutcome     string
}

func (q *Queries) ListProblemSolutions(ctx context.Context, arg ListProblemSolutionsParams) ([]ListProblemSolutionsRow, error) {
	rows, err := q.db.Query(ctx, listProblemSolutions, arg.ViewerID, arg.ProblemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProblemSolutionsRow
	for rows.Next() {
		var i ListProblemSolutionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Score,
			&i.CreatedAt,
			&i.RevisionID,
			&i.Body,
			&i.VoteCount,
			&i.RevisionCreatedAt,
			&i.IsRevised,
			&i.AuthorDisplay,
			&i.AuthorHandle,
			&i.AuthorDeleted,
			&i.AuthorTier,
			&i.ViewerIsAuthor,
			&i.ViewerVoted,
			&i.Worked,
			&i.Partly,
			&i.Failed,
			&i.RecentNotes,
			&i.ViewerOutcome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSolutionRevisionCandidates = `-- name: ListSolutionRevisionCandidates :many
SELECT id, score, vote_count FROM solution_revisions
WHERE solution_id = $1
ORDER BY score DESC, id
`

type ListSolutionRevisionCandidatesRow struct {
	ID        uuid.UUID
	Score     float64
	VoteCount int32
}

func (q *Queries) ListSolutionRevisionCandidates(ctx context.Context, solutionID uuid.UUID) ([]ListSolutionRevisionCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listSolutionRevisionCandidates, solutionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSolutionRevisionCandidatesRow
	for rows.Next() {
		var i ListSolutionRevisionCandidatesRow
		if err := rows.Scan(&i.ID, &i.Score, &i.VoteCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProblemSoftSolved = `-- name: LockProblemSoftSolved :one
SELECT soft_solved FROM problems WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockProblemSoftSolved(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, lockProblemSoftSolved, id)
	var soft_solved bool
	err := row.Scan(&soft_solved)
	return soft_solved, err
}

const lockSolutionForPick = `-- name: LockSolutionForPick :one
SELECT current_revision_id, problem_id FROM solutions WHERE id = $1 FOR UPDATE
`

type LockSolutionForPickRow struct {
	CurrentRevisionID *uuid.UUID
	ProblemID         uuid.UUID
}

func (q *Queries) LockSolutionForPick(ctx context.Context, id uuid.UUID) (LockSolutionForPickRow, error) {
	row := q.db.QueryRow(ctx, lockSolutionForPick, id)
	var i LockSolutionForPickRow
	err := row.Scan(&i.CurrentRevisionID, &i.ProblemID)
	return i, err
}

const setProblemSoftSolved = `-- name: SetProblemSoftSolved :exec
UPDATE problems SET soft_solved = $1 WHERE id = $2
`

type SetProblemSoftSolvedParams struct {
	SoftSolved bool
	ID         uuid.UUID
}

func (q *Queries) SetProblemSoftSolved(ctx context.Context, arg SetProblemSoftSolvedParams) error {
	_, err := q.db.Exec(ctx, setProblemSoftSolved, arg.SoftSolved, arg.ID)
	return err
}

const setSolutionCurrentRevision = `-- name: SetSolutionCurrentRevision :execrows
UPDATE solutions s
SET current_revision_id = r.id, score = r.score
FROM solution_revisions r
WHERE s.id = $1 AND r.id = $2 AND r.solution_id = s.id
`

type SetSolutionCurrentRevisionParams struct {
	SolutionID uuid.UUID
	RevisionID uuid.UUID
}

// One statement: current revision and the solution's score (= the leader's).
func (q *Queries) SetSolutionCurrentRevision(ctx context.Context, arg SetSolutionCurrentRevisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSolutionCurrentRevision, arg.SolutionID, arg.RevisionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertSolutionTrial = `-- name: UpsertSolutionTrial :exec
INSERT INTO solution_trials (solution_id, user_id, outcome, note, created_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (solution_id, user_id)
DO UPDATE SET outcome = EXCLUDED.outcome, note = EXCLUDED.note, created_at = EXCLUDED.created_at
`

type UpsertSolutionTrialParams struct {
	SolutionID uuid.UUID
	UserID     uuid.UUID
	Outcome    TriedOutcome
	Note       *string
	CreatedAt  time.Time
}

func (q *Queries) UpsertSolutionTrial(ctx context.Context, arg UpsertSolutionTrialParams) error {
	_, err := q.db.Exec(ctx, upsertSolutionTrial,
		arg.SolutionID,
		arg.UserID,
		arg.Outcome,
		arg.Note,
		arg.CreatedAt,
	)
	return err
}
