// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: state_votes.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const adminZeroStateVoteWeights = `-- name: AdminZeroStateVoteWeights :execrows
UPDATE problem_state_votes SET weight = 0
WHERE user_id = $1 AND weight <> 0
`

func (q *Queries) AdminZeroStateVoteWeights(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, adminZeroStateVoteWeights, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearStateVotes = `-- name: ClearStateVotes :exec
DELETE FROM problem_state_votes
WHERE problem_id = $1 AND to_state = $2
`

type ClearStateVotesParams struct {
	ProblemID uuid.UUID
	ToState   ProblemState
}

// A concluded vote is cleared, so a later reopen starts from zero.
func (q *Queries) ClearStateVotes(ctx context.Context, arg ClearStateVotesParams) error {
	_, err := q.db.Exec(ctx, clearStateVotes, arg.ProblemID, arg.ToState)
	return err
}

const deleteStateVote = `-- name: DeleteStateVote :execrows
DELETE FROM problem_state_votes
WHERE problem_id = $1 AND user_id = $2 AND to_state = $3
`

type DeleteStateVoteParams struct {
	ProblemID uuid.UUID
	UserID    uuid.UUID
	ToState   ProblemState
}

func (q *Queries) DeleteStateVote(ctx context.Context, arg DeleteStateVoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStateVote, arg.ProblemID, arg.UserID, arg.ToState)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertStateVote = `-- name: InsertStateVote :execrows
INSERT INTO problem_state_votes (problem_id, user_id, to_state, weight, created_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT DO NOTHING
`

type InsertStateVoteParams struct {
	ProblemID uuid.UUID
	UserID    uuid.UUID
	ToState   ProblemState
	Weight    float32
	CreatedAt time.Time
}

func (q *Queries) InsertStateVote(ctx context.Context, arg InsertStateVoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertStateVote,
		arg.ProblemID,
		arg.UserID,
		arg.ToState,
		arg.Weight,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockProblemForStateVote = `-- name: LockProblemForStateVote :one

SELECT p.id, p.author_id, p.domain_id, p.state,
       GREATEST(p.created_at,
                (SELECT max(e.created_at) FROM problem_state_events e
                 WHERE e.problem_id = p.id AND e.actor_id = p.author_id),
                (SELECT max(r.created_at) FROM problem_revisions r
                 WHERE r.problem_id = p.id AND r.author_id = p.author_id))::timestamptz AS poster_last_active_at
FROM problems p
WHERE p.id = $1
FOR UPDATE OF p
`

type LockProblemForStateVoteRow struct {
	ID                 uuid.UUID
	AuthorID           uuid.UUID
	DomainID           int16
	State              ProblemState
	PosterLastActiveAt time.Time
}

// Phase 4 community state vote (problem_state_votes, migration 0005).
// The problem row, locked, with when the poster last acted on it: the latest
// of its creation, the poster's own state changes and the poster's revisions.
func (q *Queries) LockProblemForStateVote(ctx context.Context, id uuid.UUID) (LockProblemForStateVoteRow, error) {
	row := q.db.QueryRow(ctx, lockProblemForStateVote, id)
	var i LockProblemForStateVoteRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.DomainID,
		&i.State,
		&i.PosterLastActiveAt,
	)
	return i, err
}

const sumStateVotes = `-- name: SumStateVotes :one
SELECT COALESCE(sum(weight), 0)::float8 AS total
FROM problem_state_votes
WHERE problem_id = $1 AND to_state = $2
`

type SumStateVotesParams struct {
	ProblemID uuid.UUID
	ToState   ProblemState
}

func (q *Queries) SumStateVotes(ctx context.Context, arg SumStateVotesParams) (float64, error) {
	row := q.db.QueryRow(ctx, sumStateVotes, arg.ProblemID, arg.ToState)
	var total float64
	err := row.Scan(&total)
	return total, err
}
