// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: votes.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addProblemRevisionScore = `-- name: AddProblemRevisionScore :one
UPDATE problem_revisions
SET score = score + $1::float8,
    vote_count = vote_count + $2::int4
WHERE id = $3
RETURNING vote_count
`

type AddProblemRevisionScoreParams struct {
	Delta      float64
	CountDelta int32
	ID         uuid.UUID
}

func (q *Queries) AddProblemRevisionScore(ctx context.Context, arg AddProblemRevisionScoreParams) (int32, error) {
	row := q.db.QueryRow(ctx, addProblemRevisionScore, arg.Delta, arg.CountDelta, arg.ID)
	var vote_count int32
	err := row.Scan(&vote_count)
	return vote_count, err
}

const addSolutionRevisionScore = `-- name: AddSolutionRevisionScore :one
UPDATE solution_revisions
SET score = score + $1::float8,
    vote_count = vote_count + $2::int4
WHERE id = $3
RETURNING vote_count
`

type AddSolutionRevisionScoreParams struct {
	Delta      float64
	CountDelta int32
	ID         uuid.UUID
}

func (q *Queries) AddSolutionRevisionScore(ctx context.Context, arg AddSolutionRevisionScoreParams) (int32, error) {
	row := q.db.QueryRow(ctx, addSolutionRevisionScore, arg.Delta, arg.CountDelta, arg.ID)
	var vote_count int32
	err := row.Scan(&vote_count)
	return vote_count, err
}

const deleteProblemRevisionVote = `-- name: DeleteProblemRevisionVote :one
DELETE FROM problem_revision_votes
WHERE revision_id = $1 AND user_id = $2
RETURNING weight, created_at
`

type DeleteProblemRevisionVoteParams struct {
	RevisionID uuid.UUID
	UserID     uuid.UUID
}

type DeleteProblemRevisionVoteRow struct {
	Weight    float32
	CreatedAt time.Time
}

func (q *Queries) DeleteProblemRevisionVote(ctx context.Context, arg DeleteProblemRevisionVoteParams) (DeleteProblemRevisionVoteRow, error) {
	row := q.db.QueryRow(ctx, deleteProblemRevisionVote, arg.RevisionID, arg.UserID)
	var i DeleteProblemRevisionVoteRow
	err := row.Scan(&i.Weight, &i.CreatedAt)
	return i, err
}

const deleteSolutionRevisionVote = `-- name: DeleteSolutionRevisionVote :one
DELETE FROM solution_revision_votes
WHERE revision_id = $1 AND user_id = $2
RETURNING weight, created_at
`

type DeleteSolutionRevisionVoteParams struct {
	RevisionID uuid.UUID
	UserID     uuid.UUID
}

type DeleteSolutionRevisionVoteRow struct {
	Weight    float32
	CreatedAt time.Time
}

func (q *Queries) DeleteSolutionRevisionVote(ctx context.Context, arg DeleteSolutionRevisionVoteParams) (DeleteSolutionRevisionVoteRow, error) {
	row := q.db.QueryRow(ctx, deleteSolutionRevisionVote, arg.RevisionID, arg.UserID)
	var i DeleteSolutionRevisionVoteRow
	err := row.Scan(&i.Weight, &i.CreatedAt)
	return i, err
}

const getProblemRevisionVoteTarget = `-- name: GetProblemRevisionVoteTarget :one

SELECT r.id, r.problem_id, r.author_id, p.domain_id, p.state
FROM problem_revisions r
JOIN problems p ON p.id = r.problem_id
WHERE r.id = $1
`

type GetProblemRevisionVoteTargetRow struct {
	ID        uuid.UUID
	ProblemID uuid.UUID
	AuthorID  uuid.UUID
	DomainID  int16
	State     ProblemState
}

// Votes attach to revisions. A vote is one row plus a single-row score
// update; RescoreAll rebuilds the stored scores from these tables.
func (q *Queries) GetProblemRevisionVoteTarget(ctx context.Context, id uuid.UUID) (GetProblemRevisionVoteTargetRow, error) {
	row := q.db.QueryRow(ctx, getProblemRevisionVoteTarget, id)
	var i GetProblemRevisionVoteTargetRow
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.AuthorID,
		&i.DomainID,
		&i.State,
	)
	return i, err
}

const getSolutionRevisionVoteTarget = `-- name: GetSolutionRevisionVoteTarget :one
SELECT sr.id, sr.solution_id, sr.author_id, s.problem_id, p.domain_id, p.state
FROM solution_revisions sr
JOIN solutions s ON s.id = sr.solution_id
JOIN problems p ON p.id = s.problem_id
WHERE sr.id = $1
`

type GetSolutionRevisionVoteTargetRow struct {
	ID         uuid.UUID
	SolutionID uuid.UUID
	AuthorID   uuid.UUID
	ProblemID  uuid.UUID
	DomainID   int16
	State      ProblemState
}

func (q *Queries) GetSolutionRevisionVoteTarget(ctx context.Context, id uuid.UUID) (GetSolutionRevisionVoteTargetRow, error) {
	row := q.db.QueryRow(ctx, getSolutionRevisionVoteTarget, id)
	var i GetSolutionRevisionVoteTargetRow
	err := row.Scan(
		&i.ID,
		&i.SolutionID,
		&i.AuthorID,
		&i.ProblemID,
		&i.DomainID,
		&i.State,
	)
	return i, err
}

const insertProblemRevisionVote = `-- name: InsertProblemRevisionVote :one
INSERT INTO problem_revision_votes (revision_id, user_id, weight, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
RETURNING weight, created_at
`

type InsertProblemRevisionVoteParams struct {
	RevisionID uuid.UUID
	UserID     uuid.UUID
	Weight     float32
	CreatedAt  time.Time
}

type InsertProblemRevisionVoteRow struct {
	Weight    float32
	CreatedAt time.Time
}

func (q *Queries) InsertProblemRevisionVote(ctx context.Context, arg InsertProblemRevisionVoteParams) (InsertProblemRevisionVoteRow, error) {
	row := q.db.QueryRow(ctx, insertProblemRevisionVote,
		arg.RevisionID,
		arg.UserID,
		arg.Weight,
		arg.CreatedAt,
	)
	var i InsertProblemRevisionVoteRow
	err := row.Scan(&i.Weight, &i.CreatedAt)
	return i, err
}

const insertSolutionRevisionVote = `-- name: InsertSolutionRevisionVote :one
INSERT INTO solution_revision_votes (revision_id, user_id, weight, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
RETURNING weight, created_at
`

type InsertSolutionRevisionVoteParams struct {
	RevisionID uuid.UUID
	UserID     uuid.UUID
	Weight     float32
	CreatedAt  time.Time
}

type InsertSolutionRevisionVoteRow struct {
	Weight    float32
	CreatedAt time.Time
}

func (q *Queries) InsertSolutionRevisionVote(ctx context.Context, arg InsertSolutionRevisionVoteParams) (InsertSolutionRevisionVoteRow, error) {
	row := q.db.QueryRow(ctx, insertSolutionRevisionVote,
		arg.RevisionID,
		arg.UserID,
		arg.Weight,
		arg.CreatedAt,
	)
	var i InsertSolutionRevisionVoteRow
	err := row.Scan(&i.Weight, &i.CreatedAt)
	return i, err
}

const listProblemRevisionVotesFor = `-- name: ListProblemRevisionVotesFor :many
SELECT revision_id, weight, created_at FROM problem_revision_votes
WHERE revision_id = ANY($1::uuid[])
`

type ListProblemRevisionVotesForRow struct {
	RevisionID uuid.UUID
	Weight     float32
	CreatedAt  time.Time
}

func (q *Queries) ListProblemRevisionVotesFor(ctx context.Context, revisionIds []uuid.UUID) ([]ListProblemRevisionVotesForRow, error) {
	rows, err := q.db.Query(ctx, listProblemRevisionVotesFor, revisionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProblemRevisionVotesForRow
	for rows.Next() {
		var i ListProblemRevisionVotesForRow
		if err := rows.Scan(&i.RevisionID, &i.Weight, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSolutionRevisionVotesFor = `-- name: ListSolutionRevisionVotesFor :many
SELECT revision_id, weight, created_at FROM solution_revision_votes
WHERE revision_id = ANY($1::uuid[])
`

type ListSolutionRevisionVotesForRow struct {
	RevisionID uuid.UUID
	Weight     float32
	CreatedAt  time.Time
}

func (q *Queries) ListSolutionRevisionVotesFor(ctx context.Context, revisionIds []uuid.UUID) ([]ListSolutionRevisionVotesForRow, error) {
	rows, err := q.db.Query(ctx, listSolutionRevisionVotesFor, revisionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSolutionRevisionVotesForRow
	for rows.Next() {
		var i ListSolutionRevisionVotesForRow
		if err := rows.Scan(&i.RevisionID, &i.Weight, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProblemRevisionsForRescore = `-- name: LockProblemRevisionsForRescore :many
SELECT r.id, r.problem_id FROM problem_revisions r
WHERE r.id > $1::uuid
  AND (NOT $2::bool OR r.problem_id = ANY($3::uuid[]))
ORDER BY r.id
LIMIT $4
FOR UPDATE
`

type LockProblemRevisionsForRescoreParams struct {
	AfterID    uuid.UUID
	OnlyListed bool
	ProblemIds []uuid.UUID
	Lim        int32
}

type LockProblemRevisionsForRescoreRow struct {
	ID        uuid.UUID
	ProblemID uuid.UUID
}

// Keyset batch (by id). FOR UPDATE makes concurrent votes on these rows wait
// until the batch's rebuilt scores are committed, so no vote is lost.
func (q *Queries) LockProblemRevisionsForRescore(ctx context.Context, arg LockProblemRevisionsForRescoreParams) ([]LockProblemRevisionsForRescoreRow, error) {
	rows, err := q.db.Query(ctx, lockProblemRevisionsForRescore,
		arg.AfterID,
		arg.OnlyListed,
		arg.ProblemIds,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockProblemRevisionsForRescoreRow
	for rows.Next() {
		var i LockProblemRevisionsForRescoreRow
		if err := rows.Scan(&i.ID, &i.ProblemID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSolutionRevisionsForRescore = `-- name: LockSolutionRevisionsForRescore :many
SELECT sr.id, sr.solution_id FROM solution_revisions sr
JOIN solutions s ON s.id = sr.solution_id
WHERE sr.id > $1::uuid
  AND (NOT $2::bool OR s.problem_id = ANY($3::uuid[]))
ORDER BY sr.id
LIMIT $4
FOR UPDATE OF sr
`

type LockSolutionRevisionsForRescoreParams struct {
	AfterID    uuid.UUID
	OnlyListed bool
	ProblemIds []uuid.UUID
	Lim        int32
}

type LockSolutionRevisionsForRescoreRow struct {
	ID         uuid.UUID
	SolutionID uuid.UUID
}

func (q *Queries) LockSolutionRevisionsForRescore(ctx context.Context, arg LockSolutionRevisionsForRescoreParams) ([]LockSolutionRevisionsForRescoreRow, error) {
	rows, err := q.db.Query(ctx, lockSolutionRevisionsForRescore,
		arg.AfterID,
		arg.OnlyListed,
		arg.ProblemIds,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockSolutionRevisionsForRescoreRow
	for rows.Next() {
		var i LockSolutionRevisionsForRescoreRow
		if err := rows.Scan(&i.ID, &i.SolutionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProblemRevisionScores = `-- name: SetProblemRevisionScores :exec
UPDATE problem_revisions r
SET score = u.score, vote_count = u.vote_count
FROM (SELECT unnest($1::uuid[]) AS id,
             unnest($2::float8[]) AS score,
             unnest($3::int4[]) AS vote_count) u
WHERE r.id = u.id
`

type SetProblemRevisionScoresParams struct {
	Ids    []uuid.UUID
	Scores []float64
	Counts []int32
}

func (q *Queries) SetProblemRevisionScores(ctx context.Context, arg SetProblemRevisionScoresParams) error {
	_, err := q.db.Exec(ctx, setProblemRevisionScores, arg.Ids, arg.Scores, arg.Counts)
	return err
}

const setSolutionRevisionScores = `-- name: SetSolutionRevisionScores :exec
UPDATE solution_revisions r
SET score = u.score, vote_count = u.vote_count
FROM (SELECT unnest($1::uuid[]) AS id,
             unnest($2::float8[]) AS score,
             unnest($3::int4[]) AS vote_count) u
WHERE r.id = u.id
`

type SetSolutionRevisionScoresParams struct {
	Ids    []uuid.UUID
	Scores []float64
	Counts []int32
}

func (q *Queries) SetSolutionRevisionScores(ctx context.Context, arg SetSolutionRevisionScoresParams) error {
	_, err := q.db.Exec(ctx, setSolutionRevisionScores, arg.Ids, arg.Scores, arg.Counts)
	return err
}
